Fixing and adding features
mljs/peak-shape-generator pull request #32
Opened 2020-12-07 13:43 UTC by jobo322

1. fixed the conversion between with between inflection points and FWHM
2. It is possible to have different fwhm for gaussian and lorentzian contribution in pseudo voigt shape
3. there is a interval option to calculate the shape values

2020-12-07 14:08 UTC, lpatiny commented on src/inflectionPointsWidthToFWHM.js
>      case 1:
Please use the constants GAUSSIAN, etc rather than 1,2,3

2020-12-07 14:11 UTC, lpatiny commented on src/inflectionPointsWidthToFWHM.js
> +      return width * Math.sqrt(3);
You could define a constant for Math.sqrt(3)

2020-12-07 14:11 UTC, lpatiny commented on src/inflectionPointsWidthToFWHM.js
> +      return width * Math.sqrt(2 * Math.LN2);
Could define a constant for Math.sqrt(2 * Math.LN2)

2020-12-07 14:12 UTC, lpatiny commented on src/inflectionPointsWidthToFWHM.js
>        return width * (mu * (Math.sqrt(2 * Math.LN2) - 1) + 1);
Define a constant for Math.sqrt(2 * Math.LN2)

2020-12-07 14:15 UTC, lpatiny requested changes
Still don't see why we should add interval

2020-12-07 14:20 UTC, jobo322 commented
before we have a step size of one between shape values. It is needed to increment density density of values.

2020-12-09 05:29 UTC, maasencioh commented on package.json
> +    "testA": "jest -i src/__tests__/gaussian.test.js",
you could add [`.only`](https://jestjs.io/docs/en/api#testonlyname-fn-timeout) to a test to do this

2020-12-09 06:28 UTC, merged